### ISSUE TITLE
Toggle total gas

### ISSUE THREAD

**Issue by prstrm** [htilburgs/MMM-MyHomeWizard#1]
Thank you for this module! It works great.

But since I don't have gas connected Total Gas is always shown as "NaN" M^3. 
Can it be made a toggle (true, false) to show or hide?

**Comment by htilburgs** [comment]
No problem, good addition. 
I Will fix It in a few days.

**Comment by htilburgs** [comment]
@prstrm Updated to v1.0.1 with the 'showGas' option.
Add this option to you're config and put it on 'false'.

`showGas: false`

**Comment by prstrm** [comment]
Thank you, this works great!
